"""Configuration management for the Wayback crawler."""

from __future__ import annotations

import json
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any

import yaml


DEFAULT_CONFIG_YAML = """\
# wayback-crawler configuration
# Generated by wayback-crawler init

database:
  path: "wayback_crawler.db"

cdx:
  base_url: "https://web.archive.org/cdx/search/cdx"
  rate_limit: 1.5
  collapse: "digest"
  match_type: "prefix"

fetcher:
  concurrency: 5
  rate_limit: 0.5
  max_retries: 3
  backoff_base: 2.0
  backoff_max: 60.0
  timeout: 30.0
  user_agent: "WaybackCrawler/1.0 (research project)"

parsers:
  twitter:
    enabled: true
    prefer_json: true
  generic:
    enabled: false

logging:
  level: "INFO"
  file: null
  format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
"""


@dataclass
class DatabaseConfig:
    path: str = "wayback_crawler.db"


@dataclass
class CdxConfig:
    base_url: str = "https://web.archive.org/cdx/search/cdx"
    rate_limit: float = 1.5
    collapse: str = "digest"
    match_type: str = "prefix"


@dataclass
class FetcherConfig:
    concurrency: int = 5
    rate_limit: float = 0.5
    max_retries: int = 3
    backoff_base: float = 2.0
    backoff_max: float = 60.0
    timeout: float = 30.0
    user_agent: str = "WaybackCrawler/1.0 (research project)"


@dataclass
class ParserToggle:
    enabled: bool = False


@dataclass
class TwitterParserToggle:
    enabled: bool = True
    prefer_json: bool = True


@dataclass
class ParsersConfig:
    twitter: TwitterParserToggle = field(default_factory=TwitterParserToggle)
    generic: ParserToggle = field(default_factory=ParserToggle)


@dataclass
class LoggingConfig:
    level: str = "INFO"
    file: str | None = None
    format: str = "%(asctime)s [%(levelname)s] %(name)s: %(message)s"


@dataclass
class Config:
    database: DatabaseConfig = field(default_factory=DatabaseConfig)
    cdx: CdxConfig = field(default_factory=CdxConfig)
    fetcher: FetcherConfig = field(default_factory=FetcherConfig)
    parsers: ParsersConfig = field(default_factory=ParsersConfig)
    logging: LoggingConfig = field(default_factory=LoggingConfig)

    def to_json(self) -> str:
        return json.dumps(self._to_dict(), indent=2, ensure_ascii=False)

    def _to_dict(self) -> dict[str, Any]:
        result: dict[str, Any] = {}
        for key, value in asdict(self).items():
            result[key] = value
        return result


def load_config(config_path: str | Path | None = None) -> Config:
    """Load configuration from a YAML file, falling back to defaults."""
    config = Config()

    if config_path is None:
        config_path = Path("config.yaml")

    path = Path(config_path)
    if path.exists():
        with open(path, encoding="utf-8") as f:
            raw = yaml.safe_load(f)
        if raw:
            _merge_config(config, raw)

    return config


def _merge_config(config: Config, raw: dict[str, Any]) -> None:
    """Recursively merge raw dict values into the Config dataclass."""
    sections = {
        "database": config.database,
        "cdx": config.cdx,
        "fetcher": config.fetcher,
        "logging": config.logging,
    }
    for section_name, section_obj in sections.items():
        if section_name in raw and isinstance(raw[section_name], dict):
            for key, value in raw[section_name].items():
                if hasattr(section_obj, key):
                    setattr(section_obj, key, value)

    if "parsers" in raw and isinstance(raw["parsers"], dict):
        parsers_raw = raw["parsers"]
        if "twitter" in parsers_raw and isinstance(parsers_raw["twitter"], dict):
            for key, value in parsers_raw["twitter"].items():
                if hasattr(config.parsers.twitter, key):
                    setattr(config.parsers.twitter, key, value)
        if "generic" in parsers_raw and isinstance(parsers_raw["generic"], dict):
            for key, value in parsers_raw["generic"].items():
                if hasattr(config.parsers.generic, key):
                    setattr(config.parsers.generic, key, value)
